[package]
name = "kespar"
version = "0.1.0"
edition = "2021"
description = "Kespar: a proof-of-concept of Cyborg's Precog — compile to bytecode, run in a VM"

[lib]
name = "kespar"
path = "src/lib.rs"

[[bin]]
name = "kespar"
path = "src/main.rs"

[dependencies]
z3 = "0.12"

[profile.release]
opt-level = 3
debug = 1
